Sam's Blog/Models/PostModel.cs
namespace samarth_blog_app.Models;

public class PostModel
{
    public int Id {get; set;} // the post ID number

    public string Title {get; set;} // the post title

    public string Body {get; set;} // the content of the post

    public DateTime CreatedtAt {get; set;} // the time the post was created

    public DateTime UpdatedAt {get; set;} // the time the post was updated (default is set to CreatedAt)
}

Sam's Blog/Models/ViewModels/ErrorViewModel.cs
namespace samarth_blog_app.Models.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Sam's Blog/Models/ViewModels/PostViewModel.cs
namespace samarth_blog_app.Models.ViewModels;

public class PostViewModel
{
    public List<PostModel> PostList {get; set;}

    public PostModel Post {get; set;}
}

Sam's Blog/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using samarth_blog_app.Models;
using samarth_blog_app.Models.ViewModels;

namespace samarth_blog_app.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Sam's Blog/Controllers/PostsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.Sqlite;
using samarth_blog_app.Models;
using samarth_blog_app.Models.ViewModels;

namespace samarth_blog_app.Controllers;

public class PostsController : Controller
{
    private readonly ILogger<PostsController> _logger;

    private readonly IConfiguration _configuration;

    public PostsController(ILogger<PostsController> logger, IConfiguration configuration)
    {
        _logger = logger;
        _configuration = configuration;
    }

    public IActionResult Index()
    {
        var postListViewModel = GetPosts();
        return View(postListViewModel);
    }

    public IActionResult NewPost()
    {
        return View();
    }

    public IActionResult ViewPost(int id)
    {
        var post = GetPostById(id);
        var postViewModel = new PostViewModel();
        postViewModel.Post = post;
        return View(postViewModel);
    }

    public IActionResult EditPost(int id)
    {
        var post = GetPostById(id);
        var postViewModel = new PostViewModel();
        postViewModel.Post = post;
        return View(postViewModel);
    }

    internal PostModel GetPostById(int id)
    {
        PostModel post = new();

        using (SqliteConnection connection = new SqliteConnection(_configuration.GetConnectionString("BlogData")))
        {
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                command.CommandText = $"SELECT * FROM post WHERE Id='{id}'";

                using (var reader = command.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            post.Id = reader.GetInt32(0);
                            post.Title = reader.GetString(1);
                            post.Body = reader.GetString(2);
                            post.CreatedtAt = reader.GetDateTime(3);
                            post.UpdatedAt = reader.GetDateTime(4);
                        }
                    } 
                    else
                    {
                        return post;
                    }
                }
            }
        }

        return post;
    }

    public ActionResult Insert(PostModel post)
    {
        post.CreatedtAt = DateTime.Now;
        post.UpdatedAt = DateTime.Now;

        using (SqliteConnection connection = new SqliteConnection(_configuration.GetConnectionString("BlogData")))
        {
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                command.CommandText = $"INSERT INTO post (title, body, createdat, updatedat) VALUES ('{post.Title }', '{post.Body}', '{post.CreatedtAt}', '{post.UpdatedAt}')";

                try {
                    command.ExecuteNonQuery();
                } catch (Exception ex) {
                    Console.WriteLine(ex.Message);
                }
            }
        }

        return RedirectToAction(nameof(Index));
    }

    public ActionResult Update(PostModel post)
    {
        post.UpdatedAt = DateTime.Now;

        using (SqliteConnection connection = new SqliteConnection(_configuration.GetConnectionString("BlogData")))
        {
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                command.CommandText = $"UPDATE post SET title='{post.Title}', body='{post.Body}', updatedat='{post.UpdatedAt}' WHERE id='{post.Id}'";
                
                try
                {
                    command.ExecuteNonQuery();
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        }

        return RedirectToAction(nameof(Index));
    }

    internal PostViewModel GetPosts()
    {
        List<PostModel> postList = new();

        using (SqliteConnection connection = new SqliteConnection(_configuration.GetConnectionString("BlogData")))
        {
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                command.CommandText = $"SELECT * FROM post";

                using (var reader = command.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            postList.Add(
                                new PostModel
                                {
                                    Id = reader.GetInt32(0),
                                    Title = reader.GetString(1),
                                    Body = reader.GetString(2),
                                    CreatedtAt = reader.GetDateTime(3),
                                    UpdatedAt = reader.GetDateTime(4)
                                }
                            );
                        }
                    } 
                    else
                    {
                        return new PostViewModel {PostList = postList};
                    }
                }
            }
        }

        return new PostViewModel
        {
            PostList = postList
        };
    }

    [HttpPost]
    public JsonResult Delete(int id)
    {
        using (SqliteConnection connection = new SqliteConnection(_configuration.GetConnectionString("BlogData")))
        {
            using (var command = connection.CreateCommand())
            {
                connection.Open();
                command.CommandText = $"DELETE from post WHERE Id='{id}'";
                command.ExecuteNonQuery();
            }
        }

        return Json(new Object{});
    }
}

Sam's Blog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Samarth's Blog</h1>
</div>

Sam's Blog/Views/Posts/EditPost.cshtml
<div class="text-center">
    <h1 class="display-4">Edit Post</h1>
</div>

@Html.Partial("_UpdateForm")

Sam's Blog/Views/Posts/Index.cshtml
@model PostViewModel

<div class="text-center">
    <h1 class="display-4">My Latest Posts</h1>
</div>

<div class="text-center">
    <a class="btn btn-primary" asp-controller="Posts" asp-action="NewPost">New Post</a>
</div>

<div class="row justify-content-center">
    <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10">
        <div class="posts-container">
        @foreach (var p in Model.PostList)
        {
            <div class="post">
                <h2><a asp-area="" asp-controller="Posts" asp-action="ViewPost" asp-route-id="@p.Id">@p.Title</a></h2>
                <h5 class="text-muted">@p.UpdatedAt</h5>
                <p>@p.Body</p>
            </div>
        }
        </div>
    </div>
</div>

Sam's Blog/Views/Posts/NewPost.cshtml
<div class="text-center">
    <h1 class="display-4">Create New Post</h1>
</div>

@Html.Partial("_InsertForm")

Sam's Blog/Views/Posts/ViewPost.cshtml
@model PostViewModel

<div class="post">
    <h2>@Model.Post.Title</h2>
    <h5>Created At: @Model.Post.CreatedtAt</h5>
    <h5>Last Modified At: @Model.Post.UpdatedAt</h5>
    <p>@Model.Post.Body</p>
</div>

<div class="post-actions">
  <ul>
    <li><a class="btn btn-primary" asp-area="" asp-controller="Posts" asp-action="EditPost" asp-route-id="@Model.Post.Id">Update</a></li>
    <li><input type="submit" class="btn btn-danger" value="Delete" onClick="deletePost(@Model.Post.Id)" /></li>
  </ul>
</div>

Sam's Blog/Views/Posts/_InsertForm.cshtml
@model PostViewModel

<form asp-action="Insert" id="form-action" method="post" class="form-horizontal" role="form">

    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10">
            <label asp-for="Post.Title" class="form-label"></label>
            <input asp-for="Post.Id" type="hidden" class="form-control" />
            <input asp-for="Post.Title" class="form-control" />
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10">
            <label asp-for="Post.Body" class="form-label"></label>
            <textarea asp-for="Post.Body" class="form-control" rows="5" cols="40"></textarea>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10 mt-3 mb-5">
            <input type="submit" id="form-button" class="btn btn-success" value="Add Post" />
        </div>
    </div>

</form>

Sam's Blog/Views/Posts/_UpdateForm.cshtml
@model PostViewModel

<form asp-action="Update" id="form-action" method="post" class="form-horizontal" role="form">

    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10">
            <label asp-for="Post.Title" class="form-label"></label>
            <input asp-for="Post.Id" type="hidden" class="form-control" />
            <input asp-for="Post.Title" class="form-control" />
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10">
            <label asp-for="Post.Body" class="form-label"></label>
            <textarea asp-for="Post.Body" class="form-control" rows="5" cols="40"></textarea>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-xl-6 col-lg-8 col-md-8 col-sm-10 mt-3 mb-5">
            <input type="submit" id="form-button" class="btn btn-success" value="Update Post" />
        </div>
    </div>

</form>

Sam's Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - samarth_blog_app</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/samarth_blog_app.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">samarth_blog_app</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - samarth_blog_app - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>